### ISSUE TITLE
Be able to check for emscripten

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/easy-wasm-c#1]
# Motivation
In order to get the Easy Wasm C project up and going, the first step will be to be able to detect if emscripten is installed and import it if it is not found or the version is insufficient.

# Tasks
- [x] Read up on sub-processes documentation.
- [x] Be able to detect if git is installed.
- [x] Be able to install git if it is not found.
- [x] Be able to detect if emscripten is installed.
- [x] If emscripten is installed, check if its version is sufficient.
- [x] If emscripten is either insufficient or not installed, git clone it into the directory.
- [x] Be able to run a script that validates both of these.
