### ISSUE TITLE
Populate README and publish to NPM

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/easy-wasm-c#11]
# Motivation
We want to publish this onto NPM as a package. Along with populating a readme to help users understand how to use this application.

# Task List
- [x] Write the README
- [x] Re-establish NPM account
- [x] Read up how to publish NPM package.
- [ ] Publish to NPM
- [ ] Verify that the package works.
