### ISSUE TITLE
Add config file during env step

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/easy-wasm-c#12]
# Motivation
We want to be able to support the config file creation during the shell script creation.

# Task Implementation
- [x] Create the config file during the env command.
- [x] Give it support flags so that it is only created if override is specified or if it does not exist.
- [x] Give it a default command.
- [x] Verify that the file was written.
