### ISSUE TITLE
Manage import function to not always overwrite.

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/easy-wasm-c#17]
# Motivation
We can accidentally delete our EMSDK directory when using our import command. We want to handle this by only overwriting if we do not already have an installation directory or if we specify a force command.

# Task Implementation
- [x] Implement flag.
- [x] Make sure that the flag is only done when the directory does not exist or when we use the force flag.
- [x] Update SDKPATH to EMSDKPATH.
- [x] update README. 
- [x] Publish version 1.0.2 to NPM.
