### ISSUE TITLE
Be able to set emscripten to the project directory

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/easy-wasm-c#3]
# Motivation
We want to be able to be able to set enscripten to the project directory as specified by the (emscripten documentation)[https://emscripten.org/docs/getting_started/downloads.html].

# Tasks
- [x] Read up on the getting started.
- [x] Be able to detect which operating system is being used and adjust the commands from there.
- [x] Be able to set the environment variables depending on the OS for the current session.
- [x] Validate that the emsdk was set.
