### ISSUE TITLE
Be able to support dynamic arguments for all commands

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/easy-wasm-c#5]
# Motivation
Instead of defaulting to the latest, we want the users to be able to set custom options for installing, activating, and updating.

# Tasks
- [x] Research commander cli
- [x] Be able to get the arguments for a command.
- [x] Be able to verify that the commands are parsed properly.
- [x] Be able to pass said dynamic options into the cli.
- [x] Verify that the parsing for dynamic options works.
