### ISSUE TITLE
Be able to compile a wasm file

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/easy-wasm-c#7]
# Motivation
We want to be able to create a setup to be able to compile a wasm file through the package.

# Task implementation
- [x] Create a config file that allows us to point to an entry file.
- [x] Be able to read from that config file.
- [x] Create a command to compile.
- [x] Check that emcc is ready before compiling.
- [x] Be able to error out properly if that happens.
- [x] Be able to interpret the command to emcc.
- [x] Be able to initiate for the compilation.
- [x] Be able to compile.
