### ISSUE TITLE
Add a command to help fully setup a new user. 

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/easy-wasm-c#9]
# Motivation
We want to be able to easily create a shell script through node that will be able to set up a new user completely fresh and new. We will do this by adding a setup command. We will also allow the user to add options to customize their setup plan for WASM.

# Task Implementation
- [x] Read up again on the procedure on making a new wasm installation
- [x] Be able to write them all down using node
- [x] Be able to write a bat and a bash file for doing both. 
- [x] Be able to execute the files.
- [x] Be able to toggle certain options on and off via the options and flags.
